### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by JonasKaad** [JonasKaad/SemesterProject-4#186]
- Jonas

**Comment by SebMon** [comment]
I believe we are supposed to write impersonal - no "we" , "I", "our", etc. So instead of:
- In this semester project we had to develop a 2D game, where we applied techniques learned from other courses, such as Component-based Software Engineering, Artificial Intelligence and Data structures and Algorithms. 

We could write:
- The goal of this semester project was to develop a 2D game by applying techniques learned from the courses: Component-Based Software Engineering, Artificial Intelligence and Data structures and Algorithms.

**Comment by SebMon** [comment]
The content in itself works well, but you switch between past, present and future tense, and whether it is written from the standpoint that we have made the game, we will make the game or we are making the game currently. I'd say the introduction should be written as "this is the idea, and this is what will be implemented". Some places you write that "We have implemented ..." but later write "we hope to make a difficult, yet fun game".
