### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Gorm2303** [JonasKaad/SemesterProject-4#223]

**Comment by AlexanderNorup** [comment]
Do you think it is possible to copy the MoSCoW table and then add an extra coloumn: `Validation` for validating the requirements? I think it would make it way more easier to read, and also to make sure that we actually cover all requirements. 


## Inspiration

![image](https://user-images.githubusercontent.com/5619812/169540916-529fa865-7333-4b4b-9b13-23dd9f7c2295.png)
The table here is made on Tablesgenerator.com. 
You can download the TGN file here: https://share.alexandernorup.com/p/Possible_Validation_Table.tgn
Then you can go to tablesgenerator.com and press "file -> load table" in order to use it as a baseline

Another inspiration screenshot of how it could be done.

![image](https://user-images.githubusercontent.com/5619812/169541404-652032db-ae61-4056-80ab-dac5e4701b47.png)

The image above is from my wiki last semester. You can find it if you use this link: https://gitlab.sdu.dk/semester-project-e2021/team-04/subscription/-/wikis/Verification

**Comment by Gorm2303** [comment]
I have made the table you asked for, it gives a great overview, but it is hard to fit more than one line of text in it.
